### ISSUE TITLE
update instances of "plug-in" to "plugin"

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity-support#11]

**Comment by SteveDaulton** [comment]
This will lead to much inconsistency in the Nyquist documentation where "plug-in" is used as a keyword in the Nyquist code.
Example:

> In this example (derived from the [High-Pass Filter](https://manual.audacityteam.org/man/high_pass_filter.html) effect), the first four lines make up the essential headers that are required in all Nyquist plug-ins.
>
>    `;nyquist plug-in `: This header tells Audacity that this file is a Nyquist plug-in.
