### ISSUE TITLE
FFMPEG homebrew instructions

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity-support#12]
currently I'm just handwaving "install homebrew and then ffmpeg", but this really needs some additional info, like: 
* opening the terminal on mac
* installing xcode
* installing homebrew
* installing ffmpeg 
* matching the architecture of Audacity (x64 audacity needs x64 ffmpeg, even on m1 macs; arm64 audacity needs arm64 ffmpeg)

**Comment by LWinterberg** [comment]
(lowering priority as arm64 binaries are now provided on buanzo.org)

**Comment by LWinterberg** [comment]
I talked to the homebrew people at FOSDEM and brought it up to date

**Comment by micsthepick** [comment]
ok, turns out https://lame.buanzo.org/ffmpeg.php provides a compatible build
