### ISSUE TITLE
Link broken on plugin support page

### ISSUE THREAD

**Issue by ThomasProbyn** [audacity/audacity-support#14]
The **Open Directory** link found at the bottom of the page: https://plugins.audacityteam.org/ is broken. Specifically the link is to the page: http://www.dmoz.org/Computers/Multimedia/Music_and_Audio/Software/Plug-ins/ which returns as a code 400 Bad Request.

**Comment by CBID2** [comment]
Hi @ThomasProbyn! Is it possible that the page that takes users to this link is broken?
