### ISSUE TITLE
Request for a preference setting to hide "Share Audio" button

### ISSUE THREAD

**Issue by bagelche** [audacity/audacity-support#15]
It's a good feature, but we have some uses on a shared computer that it is more confusing than helpful for. I'd like a preferences option to remove it from the main toolbar. Perhaps you could still make it available in a dropdown menu, either in the export submenu or as its own menu item.

**Comment by crsib** [comment]
You can disable it using `View -> Toolbars -> Share Audio Toolbar`

**Comment by bagelche** [comment]
> You can disable it using `View -> Toolbars -> Share Audio Toolbar`

You are absolutely right, thank you! I didn't think to look there though that would be logical. I am content with that option vs in preferences (and indeed it is more logical potentially).
