### ISSUE TITLE
HQ-Tone doesn't work

### ISSUE THREAD

**Issue by dlh-0492** [audacity/audacity-support#21]
Hi, I am trying to use the HQ-Tone tone generator but I keep getting this error:

`error: In BUILD-HARMONIC, 1st argument (n) must be an integer, got 2, a FLONUM`

This is what happens when I try to generate a saw or inverse saw waveform. If I try to generate a square wave, then it says "got 3" instead of "got 2".

This is on Audacity version 3.1.3.

**Comment by SteveDaulton** [comment]
If you mean this one: https://wiki.audacityteam.org/wiki/Nyquist_Generate_Plugins#HQ-Tone
it works fine for me in Audacity 3.2.3.

**Comment by dlh-0492** [comment]
Never mind. Just realised I had the wrong version installed.
