### ISSUE TITLE
Broken Link on Plugins Page

### ISSUE THREAD

**Issue by richaardvark** [audacity/audacity-support#39]
On the [Audacity Plugins page](https://plugins.audacityteam.org/), the following link referencing realtime effects is broken:

> All plugins in the **[realtime effects](https://github.com/audacity/audacity-support/blob/plugins/broken-reference/README.md)** section can be previewed in realtime in Audacity 3.2.
This means that you can change the effect settings while playing, and come back to your settings after doing many other things - without the need to undo anything.

![image](https://github.com/audacity/audacity-support/assets/41244847/fafd9b34-eb64-4385-9b94-42696e2ba72a)

**Comment by LWinterberg** [comment]
thanks! I've removed the link and updated the language on that page a bit.
