### ISSUE TITLE
Add a link to the Forum (and Support GitBook) to the Forum

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity-support#42]
Forum ELF Koz (Greg Kozikowski) wrote offline suggesting that it would be good if a link to the Manual could be added to the Audacity Forum.

_This is effectively a regression as the old Forum did have such a useful link._

To which I would add: I suggest also adding a link to the Support GitBook site.

**Comment by LWinterberg** [comment]
![image](https://github.com/audacity/audacity-support/assets/87814144/d70e6f36-42ed-4777-b4bd-e84b2423057a)
good call

**Comment by petersampsonaudacity** [comment]
Brilliant (and fast) - thanks @LWinterberg
