### ISSUE TITLE
Add note that Real-Time effects may cause recording dropouts

### ISSUE THREAD

**Issue by petersampsonaudacity** [audacity/audacity-support#49]
It may be worth adding on not on the Support page for real-time effects to the effect that they may _(but only may)_ cause recording dropouts.
https://support.audacityteam.org/audio-editing/using-realtime-effects

This emerged after I have been working offline with a user who was experiencing dropouts - he tried all the suggestions in the current FAQ:
https://manual.audacityteam.org/man/faq_recording_troubleshooting.html#skips
but to no avail.

Further experimentation led him to turning off all the real-time effects he has applied to all 11 tracks in a multi-track project. And lo and behold this cured the dropouts on recording the 12th track.

---------------------------------------------------

I have added a note to the FAQ in the 3.5.0 alpha manual:
![image](https://github.com/audacity/audacity-support/assets/50205984/e68f0447-fd06-44ba-a18d-18cc003b2eeb)

**Comment by LWinterberg** [comment]
I'd say the realtime effects is the wrong place for that, but it would be worth putting it into https://support.audacityteam.org/troubleshooting/solving-recording-problems

**Comment by LWinterberg** [comment]
It is now mentioned in https://support.audacityteam.org/troubleshooting/solving-recording-problems/recording-dropouts-gaps-skips-and-glitches
