### ISSUE TITLE
Audacity 3.5 Will Not Launch on Mac OS 10.14

### ISSUE THREAD

**Issue by ljmac** [audacity/audacity-support#54]
I understand that you only test on Mac OS 12 and later, but this version should be marked as incompatible with Mac OS 10.14 and earlier (I don't know about 10.15 and 11).

**Comment by LWinterberg** [comment]
added a note. 3.5.1 will work on older systems again.

**Comment by ljmac** [comment]
I just want to mention the 3.5.2 does indeed work on Mojave. Thank you!
