### ISSUE TITLE
Clean up nyquist reference

### ISSUE THREAD

**Issue by LWinterberg** [audacity/audacity-support#7]
The nyquist reference got ported over from the wiki, using a naive wikisyntax -> markdown conversion. These pages require manual adjustment of styles.
 
- [x] https://plugins.audacityteam.org/nyquist-plugins/creating-your-own-nyquist-plugins/plugin-reference
- [x] https://plugins.audacityteam.org/nyquist-plugins/creating-your-own-nyquist-plugins/headers-reference
- [x] https://plugins.audacityteam.org/nyquist-plugins/creating-your-own-nyquist-plugins/widgets-reference
- [x] https://plugins.audacityteam.org/nyquist-plugins/creating-your-own-nyquist-plugins/basics and subpages
- [x] https://plugins.audacityteam.org/nyquist-plugins/creating-your-own-nyquist-plugins/tutorials and subpages

NB: Gitbook dislikes being used for editing massive tables in particular. You may want to edit this locally using VSCode with markdown extensions or another text editor instead. https://github.com/audacity/audacity-support/tree/plugins/nyquist-plugins/creating-your-own-nyquist-plugins 
Gitbook Markdown is a superset of Github-flavored Markdown afaik, so anything that looks good in a local editor and in your repository will look good on the live page, too. You can see all available formatting options here: https://support.audacityteam.org/community/contributing/tutorials/gitbook-markdown-syntax

This work may be tedious, but all the information already exists. If the broken formatting leaves no clue as to what the original meaning could be like, refer to the original pages in the old wiki: https://wiki.audacityteam.org/wiki/Category:Nyquist

**Comment by SteveDaulton** [comment]
No I didn't. I couldn't get the tables to work well (too wide to fit the screen without scrolling). Unless there are tricks to Gitbook formatting that I'm not aware of, I think much of this will need rewriting with formatting that works in Gitbook. Having written most of the original content with wiki formatting, I don't want to write it again.

**Comment by LWinterberg** [comment]
Cleaned up the formatting issues in the past weeks, this is now done. Steve, you may want to take another look at it and update it/correct any remaining errors.
https://plugins.audacityteam.org/contributing/developing-your-own-plugins-and-scripts/creating-your-own-nyquist-plugins
